# Generated by Django 5.0.6 on 2024-05-23 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_APB2TAL', models.CharField(default=False, max_length=640)),
                ('archivo_hash', models.CharField(max_length=640)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('positivos', models.IntegerField()),
                ('current_time', models.DateTimeField(auto_now_add=True)),
                ('tamaño', models.CharField(default=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='adquisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivos.archivo')),
            ],
        ),
        migrations.CreateModel(
            name='Compartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivos.archivo')),
                ('grupo_destinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_grupo_destino', to='auth.group')),
                ('grupo_propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_grupo_propietario', to=settings.AUTH_USER_MODEL)),
                ('usuario_destinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_usuario_destino', to=settings.AUTH_USER_MODEL)),
                ('usuario_propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_usuario_propietario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tipomensaje', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('leido', models.BooleanField(default=False)),
                ('hora_envio', models.DateTimeField(auto_now_add=True, null=True)),
                ('enviador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enviador_mensajes', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor_mensajes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
