# Generated by Django 4.1.13 on 2024-04-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compartido',
            old_name='group',
            new_name='group_comp',
        ),
        migrations.RenameField(
            model_name='compartido',
            old_name='user',
            new_name='user_comp',
        ),
    ]
