# Generated by Django 4.1.13 on 2024-04-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_rename_group_compartido_group_comp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compartido',
            old_name='group_comp',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='compartido',
            old_name='user_comp',
            new_name='user',
        ),
    ]
