# Generated by Django 5.0.6 on 2024-05-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='nombre',
            field=models.CharField(default=None, max_length=150, unique=True, verbose_name='name'),
        ),
    ]
