# Generated by Django 5.0.6 on 2024-05-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0003_customgroup_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customgroup',
            old_name='nombre',
            new_name='namenombre',
        ),
    ]
