# Generated by Django 4.1.13 on 2024-04-22 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0014_group_description'),
        ('archivos', '0003_rename_group_comp_compartido_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compartido',
            name='group',
        ),
        migrations.RemoveField(
            model_name='compartido',
            name='user',
        ),
        migrations.AddField(
            model_name='compartido',
            name='grupo_destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_grupo_destino', to='auth.group'),
        ),
        migrations.AddField(
            model_name='compartido',
            name='grupo_propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_grupo_propietario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compartido',
            name='usuario_destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_usuario_destino', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compartido',
            name='usuario_propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_usuario_propietario', to=settings.AUTH_USER_MODEL),
        ),
    ]
