# Generated by Django 4.1.13 on 2024-05-16 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archivos', '0006_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='tipomensaje',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='enviador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enviador_mensajes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='receptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor_mensajes', to=settings.AUTH_USER_MODEL),
        ),
    ]
