# Generated by Django 4.1.13 on 2024-05-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0007_mensajes_tipomensaje_alter_mensajes_enviador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='hora_envio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
